// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5Wh-qU8LVOPBjyrhctxuKaU1RxWFm1k',
    appId: '1:277880788372:web:b6bf55677bbc1799c3eb81',
    messagingSenderId: '277880788372',
    projectId: 'olaflutter-b4aee',
    authDomain: 'olaflutter-b4aee.firebaseapp.com',
    storageBucket: 'olaflutter-b4aee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjxQ5wbNOm2dzxtlhsEAEIBiemMqGQU_I',
    appId: '1:277880788372:android:efa5201308656f3fc3eb81',
    messagingSenderId: '277880788372',
    projectId: 'olaflutter-b4aee',
    storageBucket: 'olaflutter-b4aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp6NrTv9NhN3ApE-90tOPfiwpfO5M0cuw',
    appId: '1:277880788372:ios:e3219dc817cca470c3eb81',
    messagingSenderId: '277880788372',
    projectId: 'olaflutter-b4aee',
    storageBucket: 'olaflutter-b4aee.appspot.com',
    iosClientId: '277880788372-b7piegcgtkcd7tkcjdbkp8j3tlpidrrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp6NrTv9NhN3ApE-90tOPfiwpfO5M0cuw',
    appId: '1:277880788372:ios:e3219dc817cca470c3eb81',
    messagingSenderId: '277880788372',
    projectId: 'olaflutter-b4aee',
    storageBucket: 'olaflutter-b4aee.appspot.com',
    iosClientId: '277880788372-b7piegcgtkcd7tkcjdbkp8j3tlpidrrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopAppFlutter',
  );
}
